"""Published minutes grid is generated by the canonical Python rescaler/scorer."""

import pandas as pd

from fantasy_nba.minutes_scenario import minutes_scenario
from fantasy_nba.scoring import ScoringConfig
from scripts.public_minutes import GRID, build_public_minutes


def test_exported_grid_matches_local_scenarios_and_excludes_missing_lines():
    cfg = ScoringConfig("bonus", {"pts": 1}, {"double_double": 5}, ("pts", "reb"), 10)
    board = pd.DataFrame([
        {"PLAYER_ID": 1, "PLAYER_NAME": "Projected", "mpg": 30.0, "pts": 9.0, "reb": 9.0,
         "fpts_pg": 11.0, "analyst_action": "fpts_delta:+2", "analyst_rationale": "private"},
        {"PLAYER_ID": 2, "PLAYER_NAME": "Market seed", "mpg": None, "pts": None, "reb": None,
         "fpts_pg": 20.0, "analyst_action": "none", "analyst_rationale": "private"},
    ])
    artifact = build_public_minutes(board, cfg, generated_at="2026-10-02T00:00:00+00:00", scoring_key="abc")
    assert artifact["schema"] == 1 and artifact["board_rows"] == 2
    assert list(artifact["rows"]) == ["1"]
    curve = artifact["rows"]["1"]
    assert len(curve["values"]) == len(GRID) == 84
    assert curve["retained_rate_residual"] == 2
    assert curve["values"][GRID.index(40.0)] == 19.0  # rescored 12+5 bonus, then +2 residual
    for mpg in (0.5, 30.0, 36.0, 40.0, 42.0):
        assert curve["values"][GRID.index(mpg)] == minutes_scenario(board.iloc[0].to_dict(), mpg, cfg)["assumed_fpts_pg"]
    assert "private" not in str(artifact)
